name: ShaunWhalen
favicon: null
layout_spectrum: 0.4133824398741126
typography_spectrum: 0.26771042961627245
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a446f'
    - '#42759c'
    - '#9bbad0'
    - '#000911'
  brandStrength: 0.625
  lightness: 0.2606738379690796
  saturation: 0.2217900762334466
  rhythmicContrast: 0.801496542757377
purpose: []
